# Generated by Django 4.2.10 on 2025-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_slangword_delete_slang'),
    ]

    operations = [
        migrations.AddField(
            model_name='slangword',
            name='category',
            field=models.CharField(default='uncategorized', max_length=50),
        ),
    ]
