# Generated by Django 4.2.10 on 2025-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slangword_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='slangword',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
    ]
