name: Socials API Health Check

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check Socials API Health
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://zlingo.onrender.com)
          response2=$(curl -s -o /dev/null -w "%{http_code}" https://zlinggo.onrender.com)

          if [ "$response" -eq 200 ]; then
            echo "Socials API is up and running!"
          else
            echo "Socials API returned status code $response"
          fi

          if [ "$response2" -eq 200 ]; then
            echo "New URL API is up and running!"

          else
            echo "Socials API returned status code $response"
          fi
